window.NOBEL_MEDICINE_CSV = `year,laureate,citation
1901,Emil von Behring,"for his work on serum therapy, especially its application against diphtheria, by which he has opened a new road in the domain of medical science and thereby placed in the hands of the physician a victorious weapon against illness and deaths"
1902,Ronald Ross,"for his work on malaria, by which he has shown how it enters the organism and thereby has laid the foundation for successful research on this disease and methods of combating it"
1903,Niels Ryberg Finsen,"in recognition of his contribution to the treatment of diseases, especially lupus vulgaris, with concentrated light radiation, whereby he has opened a new avenue for medical science"
1904,Ivan Pavlov,"in recognition of his work on the physiology of digestion, through which knowledge on vital aspects of the subject has been transformed and enlarged"
1905,Robert Koch,"for his investigations and discoveries in relation to tuberculosis"
1906,Camillo Golgi & Santiago Ramón y Cajal,"in recognition of their work on the structure of the nervous system"
1907,Charles Louis Alphonse Laveran,"in recognition of his work on the role played by protozoa in causing diseases"
1908,Ilya Ilyich Mechnikov & Paul Ehrlich,"in recognition of their work on immunity"
1909,Emil Theodor Kocher,"for his work on the physiology, pathology and surgery of the thyroid gland"
1910,Albrecht Kossel,"in recognition of the contributions to our knowledge of cell chemistry made through his work on proteins, including the nucleic substances"
1911,Allvar Gullstrand,"for his work on the dioptrics of the eye"
1912,Alexis Carrel,"in recognition of his work on vascular suture and the transplantation of blood vessels and organs"
1913,Charles Robert Richet,"in recognition of his work on anaphylaxis"
1914,Robert Bárány,"for his work on the physiology and pathology of the vestibular apparatus"
1919,Jules Bordet,"for his discoveries relating to immunity"
1920,Schack August Steenberg Krogh,"for his discovery of the capillary motor regulating mechanism"
1922,Archibald Vivian Hill & Otto Fritz Meyerhof,"for his discovery relating to the production of heat in the muscle / for his discovery of the fixed relationship between the consumption of oxygen and the metabolism of lactic acid in the muscle"
1923,Frederick Grant Banting & John James Rickard Macleod,"for the discovery of insulin"
1924,Willem Einthoven,"for his discovery of the mechanism of the electrocardiogram"
1926,Johannes Andreas Grib Fibiger,"for his discovery of the Spiroptera carcinoma"
1927,Julius Wagner-Jauregg,"for his discovery of the therapeutic value of malaria inoculation in the treatment of dementia paralytica"
1928,Charles Jules Henri Nicolle,"for his work on typhus"
1929,Christiaan Eijkman & Sir Frederick Gowland Hopkins,"for his discovery of the antineuritic vitamin / for his discovery of the growth-stimulating vitamins"
1930,Karl Landsteiner,"for his discovery of human blood groups"
1931,Otto Heinrich Warburg,"for his discovery of the nature and mode of action of the respiratory enzyme"
1932,Sir Charles Scott Sherrington & Edgar Douglas Adrian,"for their discoveries regarding the functions of neurons"
1933,Thomas Hunt Morgan,"for his discoveries concerning the role played by the chromosome in heredity"
1934,George Hoyt Whipple & George Richards Minot & William Parry Murphy,"for their discoveries concerning liver therapy in cases of anaemia"
1935,Hans Spemann,"for his discovery of the organizer effect in embryonic development"
1936,Sir Henry Hallett Dale & Otto Loewi,"for their discoveries relating to chemical transmission of nerve impulses"
1937,Albert von Szent-Györgyi Nagyrápolt,"for his discoveries in connection with the biological combustion processes, with special reference to vitamin C and the catalysis of fumaric acid"
1938,Corneille Jean François Heymans,"for the discovery of the role played by the sinus and aortic mechanisms in the regulation of respiration"
1939,Gerhard Domagk,"for the discovery of the antibacterial effects of prontosil"
1943,Henrik Carl Peter Dam & Edward Adelbert Doisy,"for his discovery of vitamin K / for his discovery of the chemical nature of vitamin K"
1944,Joseph Erlanger & Herbert Spencer Gasser,"for their discoveries relating to the highly differentiated functions of single nerve fibres"
1945,Sir Alexander Fleming & Ernst Boris Chain & Sir Howard Walter Florey,"for the discovery of penicillin and its curative effect in various infectious diseases"
1946,Hermann Joseph Muller,"for the discovery of the production of mutations by means of X-ray irradiation"
1947,Carl Ferdinand Cori & Gerty Theresa Cori, née Radnitz & Bernardo Alberto Houssay,"for their discovery of the course of the catalytic conversion of glycogen / for his discovery of the part played by the hormone of the anterior pituitary lobe in the metabolism of sugar"
1948,Paul Hermann Müller,"for his discovery of the high efficiency of DDT as a contact poison against several arthropods"
1949,Walter Rudolf Hess & António Caetano de Abreu Freire Egas Moniz,"for his discovery of the functional organization of the interbrain as a coordinator of the activities of the internal organs / for his discovery of the therapeutic value of leucotomy in certain psychoses"
1950,Edward Calvin Kendall & Tadeus Reichstein & Philip Showalter Hench,"for their discoveries relating to the hormones of the adrenal cortex, their structure and biological effects"
1951,Max Theiler,"for his discoveries concerning yellow fever and how to combat it"
1952,Selman Abraham Waksman,"for his discovery of streptomycin, the first antibiotic effective against tuberculosis"
1953,Hans Adolf Krebs & Fritz Albert Lipmann,"for his discovery of the citric acid cycle / for his discovery of co-enzyme A and its importance for intermediary metabolism"
1954,John Franklin Enders & Thomas Huckle Weller & Frederick Chapman Robbins,"for their discovery of the ability of poliomyelitis viruses to grow in cultures of various types of tissue"
1955,Axel Hugo Theodor Theorell,"for his discoveries concerning the nature and mode of action of oxidation enzymes"
1956,André Frédéric Cournand & Werner Forssmann & Dickinson W. Richards,"for their discoveries concerning heart catheterization and pathological changes in the circulatory system"
1957,Daniel Bovet,"for his discoveries relating to synthetic compounds that inhibit the action of certain body substances, and especially their action on the vascular system and the skeletal muscles"
1958,George Wells Beadle & Edward Lawrie Tatum & Joshua Lederberg,"for their discovery that genes act by regulating definite chemical events / for his discoveries concerning genetic recombination and the organization of the genetic material of bacteria"
1959,Severo Ochoa & Arthur Kornberg,"for their discovery of the mechanisms in the biological synthesis of ribonucleic acid and deoxyribonucleic acid"
1960,Sir Frank Macfarlane Burnet & Peter Brian Medawar,"for discovery of acquired immunological tolerance"
1961,Georg von Békésy,"for his discoveries of the physical mechanism of stimulation within the cochlea"
1962,Francis Harry Compton Crick & James Dewey Watson & Maurice Hugh Frederick Wilkins,"for their discoveries concerning the molecular structure of nucleic acids and its significance for information transfer in living material"
1963,Sir John Carew Eccles & Alan Lloyd Hodgkin & Andrew Fielding Huxley,"for their discoveries concerning the ionic mechanisms involved in excitation and inhibition in the peripheral and central portions of the nerve cell membrane"
1964,Konrad Bloch & Feodor Lynen,"for their discoveries concerning the mechanism and regulation of the cholesterol and fatty acid metabolism"
1965,François Jacob & André Lwoff & Jacques Monod,"for their discoveries concerning genetic control of enzyme and virus synthesis"
1966,Peyton Rous & Charles Brenton Huggins,"for his discovery of tumour-inducing viruses / for his discoveries concerning hormonal treatment of prostatic cancer"
1967,Ragnar Granit & Haldan Keffer Hartline & George Wald,"for their discoveries concerning the primary physiological and chemical visual processes in the eye"
1968,Robert W. Holley & Har Gobind Khorana & Marshall W. Nirenberg,"for their interpretation of the genetic code and its function in protein synthesis"
1969,Max Delbrück & Alfred D. Hershey & Salvador E. Luria,"for their discoveries concerning the replication mechanism and the genetic structure of viruses"
1970,Sir Bernard Katz & Ulf von Euler & Julius Axelrod,"for their discoveries concerning the humoral transmitters in the nerve terminals and the mechanism for their storage, release and inactivation"
1971,Earl W. Sutherland, Jr.,"for his discoveries concerning the mechanisms of the action of hormones"
1972,Gerald M. Edelman & Rodney R. Porter,"for their discoveries concerning the chemical structure of antibodies"
1973,Karl von Frisch & Konrad Lorenz & Nikolaas Tinbergen,"for their discoveries concerning organization and elicitation of individual and social behaviour patterns"
1974,Albert Claude & Christian de Duve & George E. Palade,"for their discoveries concerning the structural and functional organization of the cell"
1975,David Baltimore & Renato Dulbecco & Howard Martin Temin,"for their discoveries concerning the interaction between tumour viruses and the genetic material of the cell"
1976,Baruch S. Blumberg & D. Carleton Gajdusek,"for their discoveries concerning new mechanisms for the origin and dissemination of infectious diseases"
1977,Roger Guillemin & Andrew V. Schally & Rosalyn Yalow,"for their discoveries concerning the peptide hormone production of the brain / for the development of radioimmunoassays of peptide hormones"
1978,Werner Arber & Daniel Nathans & Hamilton O. Smith,"for the discovery of restriction enzymes and their application to problems of molecular genetics"
1979,Allan M. Cormack & Godfrey N. Hounsfield,"for the development of computer assisted tomography"
1980,Baruj Benacerraf & Jean Dausset & George D. Snell,"for their discoveries concerning genetically determined structures on the cell surface that regulate immunological reactions"
1981,Roger W. Sperry & David H. Hubel & Torsten N. Wiesel,"for his discoveries concerning the functional specialization of the cerebral hemispheres / for their discoveries concerning information processing in the visual system"
1982,Sune K. Bergström & Bengt I. Samuelsson & John R. Vane,"for their discoveries concerning prostaglandins and related biologically active substances"
1983,Barbara McClintock,"for her discovery of mobile genetic elements"
1984,Niels K. Jerne & Georges J.F. Köhler & César Milstein,"for theories concerning the specificity in development and control of the immune system and the discovery of the principle for production of monoclonal antibodies"
1985,Michael S. Brown & Joseph L. Goldstein,"for their discoveries concerning the regulation of cholesterol metabolism"
1986,Stanley Cohen & Rita Levi-Montalcini,"for their discoveries of growth factors"
1987,Susumu Tonegawa,"for his discovery of the genetic principle for generation of antibody diversity"
1988,Sir James W. Black & Gertrude B. Elion & George H. Hitchings,"for their discoveries of important principles for drug treatment"
1989,J. Michael Bishop & Harold E. Varmus,"for their discovery of the cellular origin of retroviral oncogenes"
1990,Joseph E. Murray & E. Donnall Thomas,"for their discoveries concerning organ and cell transplantation in the treatment of human disease"
1991,Erwin Neher & Bert Sakmann,"for their discoveries concerning the function of single ion channels in cells"
1992,Edmond H. Fischer & Edwin G. Krebs,"for their discoveries concerning reversible protein phosphorylation as a biological regulatory mechanism"
1993,Richard J. Roberts & Phillip A. Sharp,"for their discoveries of split genes"
1994,Alfred G. Gilman & Martin Rodbell,"for their discovery of G-proteins and the role of these proteins in signal transduction in cells"
1995,Edward B. Lewis & Christiane Nüsslein-Volhard & Eric F. Wieschaus,"for their discoveries concerning the genetic control of early embryonic development"
1996,Peter C. Doherty & Rolf M. Zinkernagel,"for their discoveries concerning the specificity of the cell mediated immune defence"
1997,Stanley B. Prusiner,"for his discovery of Prions - a new biological principle of infection"
1998,Robert F. Furchgott & Louis J. Ignarro & Ferid Murad,"for their discoveries concerning nitric oxide as a signalling molecule in the cardiovascular system"
1999,Günter Blobel,"for the discovery that proteins have intrinsic signals that govern their transport and localization in the cell"
2000,Arvid Carlsson & Paul Greengard & Eric R. Kandel,"for their discoveries concerning signal transduction in the nervous system"
2001,Leland H. Hartwell & Tim Hunt & Sir Paul M. Nurse,"for their discoveries of key regulators of the cell cycle"
2002,Sydney Brenner & H. Robert Horvitz & John E. Sulston,"for their discoveries concerning genetic regulation of organ development and programmed cell death"
2003,Paul C. Lauterbur & Sir Peter Mansfield,"for their discoveries concerning magnetic resonance imaging"
2004,Richard Axel & Linda B. Buck,"for their discoveries of odorant receptors and the organization of the olfactory system"
2005,Barry J. Marshall & J. Robin Warren,"for their discovery of the bacterium Helicobacter pylori and its role in gastritis and peptic ulcer disease"
2006,Andrew Z. Fire & Craig C. Mello,"for their discovery of RNA interference - gene silencing by double-stranded RNA"
2007,Mario R. Capecchi & Sir Martin J. Evans & Oliver Smithies,"for their discoveries of principles for introducing specific gene modifications in mice by the use of embryonic stem cells"
2008,Harald zur Hausen & Françoise Barré-Sinoussi & Luc Montagnier,"for his discovery of human papilloma viruses causing cervical cancer / for their discovery of human immunodeficiency virus"
2009,Elizabeth H. Blackburn & Carol W. Greider & Jack W. Szostak,"for the discovery of how chromosomes are protected by telomeres and the enzyme telomerase"
2010,Robert G. Edwards,"for the development of in vitro fertilization"
2011,Bruce A. Beutler & Jules A. Hoffmann & Ralph M. Steinman,"for their discoveries concerning the activation of innate immunity / for his discovery of the dendritic cell and its role in adaptive immunity"
2012,Sir John B. Gurdon & Shinya Yamanaka,"for the discovery that mature cells can be reprogrammed to become pluripotent"
2013,James E. Rothman & Randy W. Schekman & Thomas C. Südhof,"for their discoveries of machinery regulating vesicle traffic, a major transport system in our cells"
2014,John O'Keefe & May-Britt Moser & Edvard I. Moser,"for their discoveries of cells that constitute a positioning system in the brain"
2015,William C. Campbell & Satoshi Ōmura & Tu Youyou,"for their discoveries concerning a novel therapy against infections caused by roundworm parasites / for her discoveries concerning a novel therapy against Malaria"
2016,Yoshinori Ohsumi,"for his discoveries of mechanisms for autophagy"
2017,Jeffrey C. Hall & Michael Rosbash & Michael W. Young,"for their discoveries of molecular mechanisms controlling the circadian rhythm"
2018,James P. Allison & Tasuku Honjo,"for their discovery of cancer therapy by inhibition of negative immune regulation"
2019,William G. Kaelin Jr & Sir Peter J. Ratcliffe & Gregg L. Semenza,"for their discoveries of how cells sense and adapt to oxygen availability"
2020,Harvey J. Alter & Michael Houghton & Charles M. Rice,"for the discovery of Hepatitis C virus"
2021,David Julius & Ardem Patapoutian,"for their discoveries of receptors for temperature and touch"
2022,Svante Pääbo,"for his discoveries concerning the genomes of extinct hominins and human evolution"
2023,Katalin Karikó & Drew Weissman,"for their discoveries concerning nucleoside base modifications that enabled the development of effective mRNA vaccines against COVID-19"
2024,Victor Ambros & Gary Ruvkun,"for the discovery of microRNA and its role in post-transcriptional gene regulation"
2025,Mary E. Brunkow & Fred Ramsdell & Shimon Sakaguchi,"for their discoveries concerning peripheral immune tolerance"`