window.NOBEL_PHYSICS_CSV = `year,laureate,citation
1901,Wilhelm Conrad Röntgen,"In recognition of the extraordinary services he has rendered by the discovery of the remarkable rays subsequently named after him."
1902,Hendrik Lorentz & Pieter Zeeman,"In recognition of the extraordinary service they rendered by their researches into the influence of magnetism upon radiation phenomena."
1903,Antoine Henri Becquerel & Pierre Curie & Marie Curie,"In recognition of the extraordinary services he has rendered by his discovery of spontaneous radioactivity / In recognition of the extraordinary services they have rendered by their joint researches on the radiation phenomena discovered by Professor Henri Becquerel."
1904,Lord Rayleigh,"For his investigations of the densities of the most important gases and for his discovery of argon in connection with these studies."
1905,Philipp Eduard Anton von Lenard,"For his work on cathode rays."
1906,Joseph John Thomson,"In recognition of the great merits of his theoretical and experimental investigations on the conduction of electricity by gases."
1907,Albert Abraham Michelson,"For his optical precision instruments and the spectroscopic and metrological investigations carried out with their aid."
1908,Gabriel Lippmann,"For his method of reproducing colours photographically based on the phenomenon of interference."
1909,Guglielmo Marconi & Karl Ferdinand Braun,"In recognition of their contributions to the development of wireless telegraphy."
1910,Johannes Diderik van der Waals,"For his work on the equation of state for gases and liquids."
1911,Wilhelm Wien,"For his discoveries regarding the laws governing the radiation of heat."
1912,Nils Gustaf Dalén,"For his invention of automatic regulators for use in conjunction with gas accumulators for illuminating lighthouses and buoys."
1913,Heike Kamerlingh Onnes,"For his investigations on the properties of matter at low temperatures which led, inter alia, to the production of liquid helium."
1914,Max von Laue,"For his discovery of the diffraction of X-rays by crystals."
1915,William Henry Bragg & William Lawrence Bragg,"For their services in the analysis of crystal structure by means of X-rays."
1917,Charles Glover Barkla,"For his discovery of the characteristic Röntgen radiation of the elements."
1918,Max Planck,"In recognition of the services he rendered to the advancement of Physics by his discovery of energy quanta."
1919,Johannes Stark,"For his discovery of the Doppler effect in canal rays and the splitting of spectral lines in electric fields."
1920,Charles Édouard Guillaume,"In recognition of the service he has rendered to precision measurements in Physics by his discovery of anomalies in nickel steel alloys."
1921,Albert Einstein,"For his services to Theoretical Physics, and especially for his discovery of the law of the photoelectric effect."
1922,Niels Bohr,"For his services in the investigation of the structure of atoms and of the radiation emanating from them."
1923,Robert Andrews Millikan,"For his work on the elementary charge of electricity and on the photoelectric effect."
1924,Manne Siegbahn,"For his discoveries and research in the field of X-ray spectroscopy."
1925,James Franck & Gustav Hertz,"For their discovery of the laws governing the impact of an electron upon an atom."
1926,Jean Baptiste Perrin,"For his work on the discontinuous structure of matter, and especially for his discovery of sedimentation equilibrium."
1927,Arthur Holly Compton & Charles Thomson Rees Wilson,"For his discovery of the effect named after him / For his method of making the paths of electrically charged particles visible by condensation of vapour."
1928,Owen Willans Richardson,"For his work on the thermionic phenomenon and especially for the discovery of the law named after him."
1929,Louis de Broglie,"For his discovery of the wave nature of electrons."
1930,Chandrasekhara Venkata Raman,"For his work on the scattering of light and for the discovery of the effect named after him."
1932,Werner Heisenberg,"For the creation of quantum mechanics, the application of which has, inter alia, led to the discovery of the allotropic forms of hydrogen."
1933,Erwin Schrödinger & Paul Dirac,"For the discovery of new productive forms of atomic theory."
1935,James Chadwick,"For the discovery of the neutron."
1936,Victor Francis Hess & Carl David Anderson,"For his discovery of cosmic radiation / For his discovery of the positron."
1937,Clinton Joseph Davisson & George Paget Thomson,"For their experimental discovery of the diffraction of electrons by crystals."
1938,Enrico Fermi,"For his demonstrations of the existence of new radioactive elements produced by neutron irradiation, and for his related discovery of nuclear reactions brought about by slow neutrons."
1939,Ernest Orlando Lawrence,"For the invention and development of the cyclotron and for results obtained with it, especially with regard to artificial radioactive elements."
1943,Otto Stern,"For his contribution to the development of the molecular ray method and his discovery of the magnetic moment of the proton."
1944,Isidor Isaac Rabi,"For his resonance method for recording the magnetic properties of atomic nuclei."
1945,Wolfgang Pauli,"For the discovery of the Exclusion Principle, also called the Pauli Principle."
1946,Percy Williams Bridgman,"For the invention of an apparatus to produce extremely high pressures, and for the discoveries he made therewith in the field of high pressure physics."
1947,Edward Victor Appleton,"For his investigations of the physics of the upper atmosphere especially for the discovery of the so-called Appleton layer."
1948,Patrick Maynard Stuart Blackett,"For his development of the Wilson cloud chamber method, and his discoveries therewith in the fields of nuclear physics and cosmic radiation."
1949,Hideki Yukawa,"For his prediction of the existence of mesons on the basis of theoretical work on nuclear forces."
1950,Cecil Frank Powell,"For his development of the photographic method of studying nuclear processes and his discoveries regarding mesons made with this method."
1951,John Douglas Cockcroft & Ernest Thomas Sinton Walton,"For their pioneer work on the transmutation of atomic nuclei by artificially accelerated atomic particles."
1952,Felix Bloch & Edward Mills Purcell,"For their development of new methods for nuclear magnetic precision measurements and discoveries in connection therewith."
1953,Frits Zernike,"For his demonstration of the phase contrast method, especially for his invention of the phase contrast microscope."
1954,Max Born & Walther Bothe,"For his fundamental research in quantum mechanics, especially for his statistical interpretation of the wavefunction / For the coincidence method and his discoveries made therewith."
1955,Willis Eugene Lamb & Polykarp Kusch,"For his discoveries concerning the fine structure of the hydrogen spectrum / For his precision determination of the magnetic moment of the electron."
1956,William Bradford Shockley & John Bardeen & Walter Houser Brattain,"For their researches on semiconductors and their discovery of the transistor effect."
1957,Chen Ning Yang & Tsung-Dao Lee,"For their penetrating investigation of the so-called parity laws which has led to important discoveries regarding the elementary particles."
1958,Pavel Alekseyevich Cherenkov & Il´ja Mikhailovich Frank & Igor Yevgenyevich Tamm,"For the discovery and the interpretation of the Cherenkov effect."
1959,Emilio Gino Segrè & Owen Chamberlain,"For their discovery of the antiproton."
1960,Donald Arthur Glaser,"For the invention of the bubble chamber."
1961,Robert Hofstadter & Rudolf Ludwig Mössbauer,"For his pioneering studies of electron scattering in atomic nuclei and for his thereby achieved discoveries concerning the structure of the nucleons / For his researches concerning the resonance absorption of gamma radiation and his discovery in this connection of the effect which bears his name."
1962,Lev Davidovich Landau,"For his pioneering theories for condensed matter, especially liquid helium."
1963,Eugene Paul Wigner & Maria Goeppert-Mayer & J. Hans D. Jensen,"For his contributions to the theory of the atomic nucleus and the elementary particles, particularly through the discovery and application of fundamental symmetry principles / For their discoveries concerning nuclear shell structure."
1964,Charles Hard Townes & Nicolay Gennadiyevich Basov & Aleksandr Mikhailovich Prokhorov,"For fundamental work in the field of quantum electronics, which has led to the construction of oscillators and amplifiers based on the maser-laser principle."
1965,Sin-Itiro Tomonaga & Julian Schwinger & Richard P. Feynman,"For their fundamental work in quantum electrodynamics, with deep-ploughing consequences for the physics of elementary particles."
1966,Alfred Kastler,"For the discovery and development of optical methods for studying Hertzian resonances in atoms."
1967,Hans Albrecht Bethe,"For his contributions to the theory of nuclear reactions, especially his discoveries concerning the energy production in stars."
1968,Luis Walter Alvarez,"For his decisive contributions to elementary particle physics, in particular the discovery of a large number of resonance states, made possible through his development of the technique of using hydrogen bubble chamber and data analysis."
1969,Murray Gell-Mann,"For his contributions and discoveries concerning the classification of elementary particles and their interactions."
1970,Hannes Olof Gösta Alfvén & Louis Eugène Félix Néel,"For fundamental work and discoveries in magnetohydro-dynamics with fruitful applications in different parts of plasma physics / For fundamental work and discoveries concerning antiferromagnetism and ferrimagnetism which have led to important applications in solid state physics."
1971,Dennis Gabor,"For his invention and development of the holographic method."
1972,John Bardeen & Leon Neil Cooper & John Robert Schrieffer,"For their jointly developed theory of superconductivity, usually called the BCS-theory."
1973,Leo Esaki & Ivar Giaever & Brian David Josephson,"For their experimental discoveries regarding tunneling phenomena in semiconductors and superconductors, respectively / For his theoretical predictions of the properties of a supercurrent through a tunnel barrier, in particular those phenomena which are generally known as the Josephson effects."
1974,Martin Ryle & Antony Hewish,"For their pioneering research in radio astrophysics: Ryle for his observations and inventions, in particular of the aperture synthesis technique, and Hewish for his decisive role in the discovery of pulsars."
1975,Aage Niels Bohr & Ben Roy Mottelson & Leo James Rainwater,"For the discovery of the connection between collective motion and particle motion in atomic nuclei and the development of the theory of the structure of the atomic nucleus based on this connection."
1976,Burton Richter & Samuel Chao Chung Ting,"For their pioneering work in the discovery of a heavy elementary particle of a new kind."
1977,Philip Warren Anderson & Nevill Francis Mott & John Hasbrouck Van Vleck,"For their fundamental theoretical investigations of the electronic structure of magnetic and disordered systems."
1978,Arno Allan Penzias & Robert Woodrow Wilson & Pyotr Leonidovich Kapitsa,"For their discovery of cosmic microwave background radiation / For his basic inventions and discoveries in the area of low-temperature physics."
1979,Sheldon Lee Glashow & Abdus Salam & Steven Weinberg,"For their contributions to the theory of the unified weak and electromagnetic interaction between elementary particles, including, inter alia, the prediction of the weak neutral current."
1980,James Watson Cronin & Val Logsdon Fitch,"For the discovery of violations of fundamental symmetry principles in the decay of neutral K-mesons."
1981,Nicolaas Bloembergen & Arthur Leonard Schawlow & Kai Manne Börje Siegbahn,"For their contribution to the development of laser spectroscopy / For his contribution to the development of high-resolution electron spectroscopy."
1982,Kenneth Geddes Wilson,"For his theory for critical phenomena in connection with phase transitions."
1983,Subrahmanyan Chandrasekhar & William Alfred Fowler,"For his theoretical studies of the physical processes of importance to the structure and evolution of the stars / For his theoretical and experimental studies of the nuclear reactions of importance in the formation of the chemical elements in the universe."
1984,Carlo Rubbia & Simon van der Meer,"For their decisive contributions to the large project, which led to the discovery of the field particles W and Z, communicators of weak interaction."
1985,Klaus von Klitzing,"For the discovery of the quantized Hall effect."
1986,Ernst Ruska & Gerd Binnig & Heinrich Rohrer,"For his fundamental work in electron optics, and for the design of the first electron microscope / For their design of the scanning tunneling microscope."
1987,J. Georg Bednorz & K. Alexander Müller,"For their important break-through in the discovery of superconductivity in ceramic materials."
1988,Leon M. Lederman & Melvin Schwartz & Jack Steinberger,"For the neutrino beam method and the demonstration of the doublet structure of the leptons through the discovery of the muon neutrino."
1989,Norman F. Ramsey & Hans G. Dehmelt & Wolfgang Paul,"For the invention of the separated oscillatory fields method and its use in the hydrogen maser and other atomic clocks / For the development of the ion trap technique."
1990,Jerome I. Friedman & Henry W. Kendall & Richard E. Taylor,"For their pioneering investigations concerning deep inelastic scattering of electrons on protons and bound neutrons, which have been of essential importance for the development of the quark model in particle physics."
1991,Pierre-Gilles de Gennes,"For discovering that methods developed for studying order phenomena in simple systems can be generalized to more complex forms of matter, in particular to liquid crystals and polymers."
1992,Georges Charpak,"For his invention and development of particle detectors, in particular the multiwire proportional chamber."
1993,Russell A. Hulse & Joseph H. Taylor Jr.,"For the discovery of a new type of pulsar, a discovery that has opened up new possibilities for the study of gravitation."
1994,Bertram N. Brockhouse & Clifford G. Shull,"For pioneering contributions to the development of neutron scattering techniques for studies of condensed matter / For pioneering contributions to the development of the neutron diffraction technique."
1995,Martin L. Perl & Frederick Reines,"For the discovery of the tau lepton / For the detection of the neutrino."
1996,David M. Lee & Douglas D. Osheroff & Robert C. Richardson,"For their discovery of superfluidity in helium-3."
1997,Steven Chu & Claude Cohen-Tannoudji & William D. Phillips,"For development of methods to cool and trap atoms with laser light."
1998,Robert B. Laughlin & Horst L. Störmer & Daniel C. Tsui,"For their discovery of a new form of quantum fluid with fractionally charged excitations."
1999,Gerardus 't Hooft & Martinus J. G. Veltman,"For elucidating the quantum structure of electroweak interactions in physics."
2000,Zhores I. Alferov & Herbert Kroemer & Jack S. Kilby,"For developing semiconductor heterostructures used in high-speed- and opto-electronics / For his part in the invention of the integrated circuit."
2001,Eric A. Cornell & Wolfgang Ketterle & Carl E. Wieman,"For the achievement of Bose-Einstein condensation in dilute gases of alkali atoms, and for early fundamental studies of the properties of the condensates."
2002,Raymond Davis Jr. & Masatoshi Koshiba & Riccardo Giacconi,"For pioneering contributions to astrophysics, in particular for the detection of cosmic neutrinos / For pioneering contributions to astrophysics, which have led to the discovery of cosmic X-ray sources."
2003,Alexei A. Abrikosov & Vitaly L. Ginzburg & Anthony J. Leggett,"For pioneering contributions to the theory of superconductors and superfluids."
2004,David J. Gross & H. David Politzer & Frank Wilczek,"For the discovery of asymptotic freedom in the theory of the strong interaction."
2005,Roy J. Glauber & John L. Hall & Theodor W. Hänsch,"For his contribution to the quantum theory of optical coherence / For their contributions to the development of laser-based precision spectroscopy, including the optical frequency comb technique."
2006,John C. Mather & George F. Smoot,"For their discovery of the blackbody form and anisotropy of the cosmic microwave background radiation."
2007,Albert Fert & Peter Grünberg,"For the discovery of Giant Magnetoresistance."
2008,Yoichiro Nambu & Makoto Kobayashi & Toshihide Maskawa,"For the discovery of the mechanism of spontaneous broken symmetry in subatomic physics / For the discovery of the origin of the broken symmetry which predicts the existence of at least three families of quarks in nature."
2009,Charles K. Kao & Willard S. Boyle & George E. Smith,"For groundbreaking achievements concerning the transmission of light in fibers for optical communication / For the invention of an imaging semiconductor circuit – the CCD sensor."
2010,Andre Geim & Konstantin Novoselov,"For groundbreaking experiments regarding the two-dimensional material graphene."
2011,Saul Perlmutter & Brian P. Schmidt & Adam G. Riess,"For the discovery of the accelerating expansion of the Universe through observations of distant supernovae."
2012,Serge Haroche & David J. Wineland,"For ground-breaking experimental methods that enable measuring and manipulation of individual quantum systems."
2013,François Englert & Peter W. Higgs,"For the theoretical discovery of a mechanism that contributes to our understanding of the origin of mass of subatomic particles, and which recently was confirmed through the discovery of the predicted fundamental particle, by the ATLAS and CMS experiments at CERN's Large Hadron Collider."
2014,Isamu Akasaki & Hiroshi Amano & Shuji Nakamura,"For the invention of efficient blue light-emitting diodes which has enabled bright and energy-saving white light sources."
2015,Takaaki Kajita & Arthur B. McDonald,"For the discovery of neutrino oscillations, which shows that neutrinos have mass."
2016,David J. Thouless & F. Duncan M. Haldane & J. Michael Kosterlitz,"For theoretical discoveries of topological phase transitions and topological phases of matter."
2017,Rainer Weiss & Barry C. Barish & Kip S. Thorne,"For decisive contributions to the LIGO detector and the observation of gravitational waves."
2018,Arthur Ashkin & Gérard Mourou & Donna Strickland,"For the optical tweezers and their application to biological systems / For their method of generating high-intensity, ultra-short optical pulses."
2019,James Peebles & Michel Mayor & Didier Queloz,"For theoretical discoveries in physical cosmology / For the discovery of an exoplanet orbiting a solar-type star."
2020,Roger Penrose & Reinhard Genzel & Andrea Ghez,"For the discovery that black hole formation is a robust prediction of the general theory of relativity / For the discovery of a supermassive compact object at the centre of our galaxy."
2021,Syukuro Manabe & Klaus Hasselmann & Giorgio Parisi,"For the physical modelling of Earth's climate, quantifying variability and reliably predicting global warming / For the discovery of the interplay of disorder and fluctuations in physical systems from atomic to planetary scales."
2022,Alain Aspect & John F. Clauser & Anton Zeilinger,"For experiments with entangled photons, establishing the violation of Bell inequalities and pioneering quantum information science."
2023,Pierre Agostini & Ferenc Krausz & Anne L'Huillier,"For experimental methods that generate attosecond pulses of light for the study of electron dynamics in matter."
2024,John J. Hopfield & Geoffrey E. Hinton,"For foundational discoveries and inventions that enable machine learning with artificial neural networks."
2025,John Clarke & Michel H. Devoret & John M. Martinis,"For the discovery of macroscopic quantum mechanical tunnelling and energy quantisation in an electric circuit."`
