window.NOBEL_CHEMISTRY_CSV = `year,laureate,citation
1901,Jacobus Henricus van 't Hoff,"in recognition of the extraordinary services he has rendered by the discovery of the laws of chemical dynamics and osmotic pressure in solutions"
1902,Hermann Emil Fischer,"in recognition of the extraordinary services he has rendered by his work on sugar and purine syntheses"
1903,Svante August Arrhenius,"in recognition of the extraordinary services he has rendered to the advancement of chemistry by his electrolytic theory of dissociation"
1904,Sir William Ramsay,"in recognition of his services in the discovery of the inert gaseous elements in air, and his determination of their place in the periodic system"
1905,Johann Friedrich Wilhelm Adolf von Baeyer,"in recognition of his services in the advancement of organic chemistry and the chemical industry, through his work on organic dyes and hydroaromatic compounds"
1906,Henri Moissan,"in recognition of the great services rendered by him in his investigation and isolation of the element fluorine, and for the adoption in the service of science of the electric furnace called after him"
1907,Eduard Buchner,"for his biochemical researches and his discovery of cell-free fermentation"
1908,Ernest Rutherford,"for his investigations into the disintegration of the elements, and the chemistry of radioactive substances"
1909,Wilhelm Ostwald,"in recognition of his work on catalysis and for his investigations into the fundamental principles governing chemical equilibria and rates of reaction"
1910,Otto Wallach,"in recognition of his services to organic chemistry and the chemical industry by his pioneer work in the field of alicyclic compounds"
1911,Marie Curie,"in recognition of her services to the advancement of chemistry by the discovery of the elements radium and polonium, by the isolation of radium and the study of the nature and compounds of this remarkable element"
1912,Victor Grignard & Paul Sabatier,"for the discovery of the so-called Grignard reagent, which in recent years has greatly advanced the progress of organic chemistry / for his method of hydrogenating organic compounds in the presence of finely disintegrated metals whereby the progress of organic chemistry has been greatly advanced in recent years"
1913,Alfred Werner,"in recognition of his work on the linkage of atoms in molecules by which he has thrown new light on earlier investigations and opened up new fields of research especially in inorganic chemistry"
1914,Theodore William Richards,"in recognition of his accurate determinations of the atomic weight of a large number of chemical elements"
1915,Richard Martin Willstätter,"for his researches on plant pigments, especially chlorophyll"
1918,Fritz Haber,"for the synthesis of ammonia from its elements"
1920,Walther Hermann Nernst,"in recognition of his work in thermochemistry"
1921,Frederick Soddy,"for his contributions to our knowledge of the chemistry of radioactive substances, and his investigations into the origin and nature of isotopes"
1922,Francis William Aston,"for his discovery, by means of his mass spectrograph, of isotopes, in a large number of non-radioactive elements, and for his enunciation of the whole-number rule"
1923,Fritz Pregl,"for his invention of the method of micro-analysis of organic substances"
1925,Richard Adolf Zsigmondy,"for his demonstration of the heterogenous nature of colloid solutions and for the methods he used, which have since become fundamental in modern colloid chemistry"
1926,The (Theodor) Svedberg,"for his work on disperse systems"
1927,Heinrich Otto Wieland,"for his investigations of the constitution of the bile acids and related substances"
1928,Adolf Otto Reinhold Windaus,"for the services rendered through his research into the constitution of the sterols and their connection with the vitamins"
1929,Arthur Harden & Hans Karl August Simon von Euler-Chelpin,"for their investigations on the fermentation of sugar and fermentative enzymes"
1930,Hans Fischer,"for his researches into the constitution of haemin and chlorophyll and especially for his synthesis of haemin"
1931,Carl Bosch & Friedrich Bergius,"in recognition of their contributions to the invention and development of chemical high pressure methods"
1932,Irving Langmuir,"for his discoveries and investigations in surface chemistry"
1934,Harold Clayton Urey,"for his discovery of heavy hydrogen"
1935,Frédéric Joliot & Irène Joliot-Curie,"in recognition of their synthesis of new radioactive elements"
1936,Petrus (Peter) Josephus Wilhelmus Debye,"for his contributions to our knowledge of molecular structure through his investigations on dipole moments and on the diffraction of X-rays and electrons in gases"
1937,Walter Norman Haworth & Paul Karrer,"for his investigations on carbohydrates and vitamin C / for his investigations on carotenoids, flavins and vitamins A and B2"
1938,Richard Kuhn,"for his work on carotenoids and vitamins"
1939,Adolf Friedrich Johann Butenandt & Leopold Ruzicka,"for his work on sex hormones / for his work on polymethylenes and higher terpenes"
1943,George de Hevesy,"for his work on the use of isotopes as tracers in the study of chemical processes"
1944,Otto Hahn,"for his discovery of the fission of heavy nuclei"
1945,Artturi Ilmari Virtanen,"for his research and inventions in agricultural and nutrition chemistry, especially for his fodder preservation method"
1946,James Batcheller Sumner & John Howard Northrop & Wendell Meredith Stanley,"for his discovery that enzymes can be crystallized / for their preparation of enzymes and virus proteins in a pure form"
1947,Sir Robert Robinson,"for his investigations on plant products of biological importance, especially the alkaloids"
1948,Arne Wilhelm Kaurin Tiselius,"for his research on electrophoresis and adsorption analysis, especially for his discoveries concerning the complex nature of the serum proteins"
1949,William Francis Giauque,"for his contributions in the field of chemical thermodynamics, particularly concerning the behaviour of substances at extremely low temperatures"
1950,Otto Paul Hermann Diels & Kurt Alder,"for their discovery and development of the diene synthesis"
1951,Edwin Mattison McMillan & Glenn Theodore Seaborg,"for their discoveries in the chemistry of the transuranium elements"
1952,Archer John Porter Martin & Richard Laurence Millington Synge,"for their invention of partition chromatography"
1953,Hermann Staudinger,"for his discoveries in the field of macromolecular chemistry"
1954,Linus Carl Pauling,"for his research into the nature of the chemical bond and its application to the elucidation of the structure of complex substances"
1955,Vincent du Vigneaud,"for his work on biochemically important sulphur compounds, especially for the first synthesis of a polypeptide hormone"
1956,Sir Cyril Norman Hinshelwood & Nikolay Nikolaevich Semenov,"for their researches into the mechanism of chemical reactions"
1957,Lord (Alexander R.) Todd,"for his work on nucleotides and nucleotide co-enzymes"
1958,Frederick Sanger,"for his work on the structure of proteins, especially that of insulin"
1959,Jaroslav Heyrovsky,"for his discovery and development of the polarographic methods of analysis"
1960,Willard Frank Libby,"for his method to use carbon-14 for age determination in archaeology, geology, geophysics, and other branches of science"
1961,Melvin Calvin,"for his research on the carbon dioxide assimilation in plants"
1962,Max Ferdinand Perutz & John Cowdery Kendrew,"for their studies of the structures of globular proteins"
1963,Karl Ziegler & Giulio Natta,"for their discoveries in the field of the chemistry and technology of high polymers"
1964,Dorothy Crowfoot Hodgkin,"for her determinations by X-ray techniques of the structures of important biochemical substances"
1965,Robert Burns Woodward,"for his outstanding achievements in the art of organic synthesis"
1966,Robert Sanderson Mulliken,"for his fundamental work concerning chemical bonds and the electronic structure of molecules by the molecular orbital method"
1967,Manfred Eigen & Ronald George Wreyford Norrish & George Porter,"for their studies of extremely fast chemical reactions, effected by disturbing the equilibrium by means of very short pulses of energy"
1968,Lars Onsager,"for the discovery of the reciprocal relations bearing his name, which are fundamental for the thermodynamics of irreversible processes"
1969,Derek Harold Richard Barton & Odd Hassel,"for their contributions to the development of the concept of conformation and its application in chemistry"
1970,Luis Federico Leloir,"for his discovery of sugar nucleotides and their role in the biosynthesis of carbohydrates"
1971,Gerhard Herzberg,"for his contributions to the knowledge of electronic structure and geometry of molecules, particularly free radicals"
1972,Christian Boehmer Anfinsen & Stanford Moore & William Howard Stein,"for his work on ribonuclease, especially concerning the connection between the amino acid sequence and the biologically active conformation / for their contribution to the understanding of the connection between chemical structure and catalytic activity of the active centre of the ribonuclease molecule"
1973,Ernst Otto Fischer & Geoffrey Wilkinson,"for their pioneering work, performed independently, on the chemistry of the organometallic, so called sandwich compounds"
1974,Paul J. Flory,"for his fundamental achievements, both theoretical and experimental, in the physical chemistry of the macromolecules"
1975,John Warcup Cornforth & Vladimir Prelog,"for his work on the stereochemistry of enzyme-catalyzed reactions / for his research into the stereochemistry of organic molecules and reactions"
1976,William Lipscomb,"for his studies on the structure of boranes illuminating problems of chemical bonding"
1977,Ilya Prigogine,"for his contributions to non-equilibrium thermodynamics, particularly the theory of dissipative structures"
1978,Peter D. Mitchell,"for his contribution to the understanding of biological energy transfer through the formulation of the chemiosmotic theory"
1979,Herbert C. Brown & Georg Wittig,"for their development of the use of boron- and phosphorus-containing compounds, respectively, into important reagents in organic synthesis"
1980,Paul Berg & Walter Gilbert & Frederick Sanger,"for his fundamental studies of the biochemistry of nucleic acids, with particular regard to recombinant-DNA / for their contributions concerning the determination of base sequences in nucleic acids"
1981,Kenichi Fukui & Roald Hoffmann,"for their theories, developed independently, concerning the course of chemical reactions"
1982,Aaron Klug,"for his development of crystallographic electron microscopy and his structural elucidation of biologically important nucleic acid-protein complexes"
1983,Henry Taube,"for his work on the mechanisms of electron transfer reactions, especially in metal complexes"
1984,Bruce Merrifield,"for his development of methodology for chemical synthesis on a solid matrix"
1985,Herbert A. Hauptman & Jerome Karle,"for their outstanding achievements in the development of direct methods for the determination of crystal structures"
1986,Dudley R. Herschbach & Yuan T. Lee & John C. Polanyi,"for their contributions concerning the dynamics of chemical elementary processes"
1987,Donald J. Cram & Jean-Marie Lehn & Charles J. Pedersen,"for their development and use of molecules with structure-specific interactions of high selectivity"
1988,Johann Deisenhofer & Robert Huber & Hartmut Michel,"for the determination of the three-dimensional structure of a photosynthetic reaction centre"
1989,Sidney Altman & Thomas R. Cech,"for their discovery of catalytic properties of RNA"
1990,Elias James Corey,"for his development of the theory and methodology of organic synthesis"
1991,Richard R. Ernst,"for his contributions to the development of the methodology of high resolution nuclear magnetic resonance (NMR) spectroscopy"
1992,Rudolph A. Marcus,"for his contributions to the theory of electron transfer reactions in chemical systems"
1993,Kary B. Mullis & Michael Smith,"for his invention of the polymerase chain reaction (PCR) method / for his fundamental contributions to the establishment of oligonucleotide-based, site-directed mutagenesis and its development for protein studies"
1994,George A. Olah,"for his contribution to carbocation chemistry"
1995,Paul J. Crutzen & Mario J. Molina & F. Sherwood Rowland,"for their work in atmospheric chemistry, particularly concerning the formation and decomposition of ozone"
1996,Robert F. Curl Jr. & Sir Harold W. Kroto & Richard E. Smalley,"for their discovery of fullerenes"
1997,Paul D. Boyer & John E. Walker & Jens C. Skou,"for their elucidation of the enzymatic mechanism underlying the synthesis of adenosine triphosphate (ATP) / for the first discovery of an ion-transporting enzyme, Na+, K+ -ATPase"
1998,Walter Kohn & John A. Pople,"for his development of the density-functional theory / for his development of computational methods in quantum chemistry"
1999,Ahmed H. Zewail,"for his studies of the transition states of chemical reactions using femtosecond spectroscopy"
2000,Alan J. Heeger & Alan G. MacDiarmid & Hideki Shirakawa,"for the discovery and development of conductive polymers"
2001,William S. Knowles & Ryoji Noyori & K. Barry Sharpless,"for their work on chirally catalysed hydrogenation reactions / for his work on chirally catalysed oxidation reactions"
2002,John B. Fenn & Koichi Tanaka & Kurt Wüthrich,"for their development of soft desorption ionisation methods for mass spectrometric analyses of biological macromolecules / for his development of nuclear magnetic resonance spectroscopy for determining the three-dimensional structure of biological macromolecules in solution"
2003,Peter Agre & Roderick MacKinnon,"for discoveries concerning channels in cell membranes / for structural and mechanistic studies of ion channels"
2004,Aaron Ciechanover & Avram Hershko & Irwin Rose,"for the discovery of ubiquitin-mediated protein degradation"
2005,Yves Chauvin & Richard R. Schrock & Robert H. Grubbs,"for the development of the metathesis method in organic synthesis"
2006,Roger D. Kornberg,"for his studies of the molecular basis of eukaryotic transcription"
2007,Gerhard Ertl,"for his studies of chemical processes on solid surfaces"
2008,Osamu Shimomura & Martin Chalfie & Roger Y. Tsien,"for the discovery and development of the green fluorescent protein, GFP"
2009,Venkatraman Ramakrishnan & Thomas A. Steitz & Ada E. Yonath,"for studies of the structure and function of the ribosome"
2010,Richard F. Heck & Ei-ichi Negishi & Akira Suzuki,"for palladium-catalyzed cross couplings in organic synthesis"
2011,Dan Shechtman,"for the discovery of quasicrystals"
2012,Robert J. Lefkowitz & Brian K. Kobilka,"for studies of G-protein-coupled receptors"
2013,Martin Karplus & Michael Levitt & Arieh Warshel,"for the development of multiscale models for complex chemical systems"
2014,Eric Betzig & Stefan W. Hell & William E. Moerner,"for the development of super-resolved fluorescence microscopy"
2015,Tomas Lindahl & Paul Modrich & Aziz Sancar,"for mechanistic studies of DNA repair"
2016,Jean-Pierre Sauvage & Sir J. Fraser Stoddart & Bernard L. Feringa,"for the design and synthesis of molecular machines"
2017,Jacques Dubochet & Joachim Frank & Richard Henderson,"for developing cryo-electron microscopy for the high-resolution structure determination of biomolecules in solution"
2018,Frances H. Arnold & George P. Smith & Sir Gregory P. Winter,"for the directed evolution of enzymes / for the phage display of peptides and antibodies"
2019,John B. Goodenough & M. Stanley Whittingham & Akira Yoshino,"for the development of lithium-ion batteries"
2020,Emmanuelle Charpentier & Jennifer A. Doudna,"for the development of a method for genome editing"
2021,Benjamin List & David W.C. MacMillan,"for the development of asymmetric organocatalysis"
2022,Carolyn R. Bertozzi & Morten Meldal & K. Barry Sharpless,"for the development of click chemistry and bioorthogonal chemistry"
2023,Moungi G. Bawendi & Louis E. Brus & Alexei I. Ekimov,"for the discovery and synthesis of quantum dots"
2024,David Baker & Demis Hassabis & John M. Jumper,"for computational protein design / for protein structure prediction"
2025,Susumu Kitagawa & Richard Robson & Omar M. Yaghi,"for the development of metal-organic frameworks"`